
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: finance_tracker_db
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wp -d finance_tracker_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://wp:wp@db:5432/finance_tracker_db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: